// Code generated by hamr gen static; DO NOT EDIT.

package components

// StaticManifest maps original asset paths to fingerprinted paths.
var StaticManifest = map[string]string{
	"css/output.css": "css/output.e7629bfa7617.css",
	"js/htmx.min.js": "js/htmx.min.e209dda5c823.js",
	"js/idiomorph.min.js": "js/idiomorph.min.cfbc37ff80a7.js",
	"js/main.js": "js/main.9d69b3f565ac.js",
	"js/nav.js": "js/nav.f4017a70cfcc.js",
	"js/ws.js": "js/ws.a52c0d4e3a5a.js",
}
