BEGIN;
DROP TABLE IF EXISTS event_exceptions;
ALTER TABLE events DROP COLUMN IF EXISTS rrule;
ALTER TABLE events DROP COLUMN IF EXISTS exdates;
ALTER TABLE events DROP COLUMN IF EXISTS rdates;
COMMIT;
